import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Main from "../components/main";
import About from "../components/about";
import Skills from "../components/skills";
import Projects from "../components/projects";
import Projects2 from "../components/projects2";
import Contact from "../components/contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Azeem Aijaz | Portfolio</title>
        <meta name="description" content="generated by next app" />
      </Head>

      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
